### ISSUE TITLE
RR: Reservation Edit and Add bypasses Approval Groups

### ISSUE THREAD

**Issue by smross** [CentralAZ/Rock-CentralAZ#65] opened 2018-03-13 14:15 UTC
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
Editing an approved reservation request and adding a resource or location that has a linked approval group bypasses the approval process

### Steps to Reproduce

1. Create a reservation request. Do not select a location that has a linked approval group
2. Request is approved
3. As the original requestor, edit the original request, adding a location or resource that has an approval group linked

**Expected behavior:** 
I expect the approval process to be followed, preferably with the request switching back to the unapproved state

**Actual behavior:** 
The reservation request keeps it's 'approved' state, and the locations/resources that were added (and have linked approval groups) are also approved. This has the side effect of not notifying the approval groups. For example, those people would not know at that point that the Resource/Location needs technical support for the reservation request

### Versions

* **Rock Version:** 6.9  
* **Client Culture Setting:** en-US

**Comment by tcavaletto** [comment] 2018-07-28 04:00
Can't reproduce on v1.3, so we're marking this as being fixed in that release

**Closed as completed by tcavaletto** 2018-07-28 04:00 UTC
Labels: bug, Room Management
